### ISSUE TITLE
how to load the embedding file?

### ISSUE THREAD

**Issue by wen-fei** [r-mal/umls-embeddings#1]
hi, thanks for you great work. i want to know how to load the embedding file? i find the save method in the code is xxx.npz, but the file you upload is xxx.csv.zip. i read the csv file but the UnicodeDecodeError appears.

**Comment by r-mal** [comment]
Sorry about that, should be fixed now.
The file is a csv where the first column contains a string CUI/TUI/relation and the rest of each row is the embedding for that CUI/TUI/relation.

**Comment by cpmss521** [comment]
UMLS embedding relation  in the first colum like `'RO:has_presentation_strength_denominator_unit', 'RO:disease_is_stage'`, but i obtain relation in abbreviation like `"'PAR', 'SY', 'CHD'"` by UMLS , so  how to map this relation ?  Thanks.

**Comment by cpmss521** [comment]
@r-mal
