### ISSUE TITLE
"embeddings.csv" cannot be opened

### ISSUE THREAD

**Issue by HiJiang** [r-mal/umls-embeddings#2]
Could you provide  "embeddings.csv"?

**Comment by wangweifeng2018** [comment]
It's a large zipped file uploaded by git lfs, therefore you must download it as fellow before you unzip it.
$ git lfs pull

It work for me, Good luck.

-----
这个是大>100M 的文件，作者上传的时候用到了 git lfs ，所以在解压前需要用 git lfs pull 到本地。
